### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by berbiche** [starcraft66/attention-attention#1]
See title

**Comment by starcraft66** [comment]
Yes, as you found out "0day" is not a valid username. I wonder which tool permitted you to create it in the first place. Note that not permitting numeric first characters is done on purpose: to avoid ambiguities between numeric UID and textual user names.

systemd will validate all configuration data you drop at it, making it hard to generate invalid configuration. Hence, yes, it's a feature that we don't permit invalid user names, and I'd consider it a limitation of xinetd that it doesn't refuse an invalid username.

So, yeah, I don't think there's anything to fix in systemd here. I understand this is annoying, but still: the username is clearly not valid.

I hope that makes sense?

**Comment by berbiche** [comment]
Please, reconsider.
I have an important business that benefits from your free work. Real enterprise customers!!!
